"""
Professional Pesticide and Chemical Database
Real-world products, active ingredients, and label information for corn/soybean consulting
"""

# ============================================================================
# INSECTICIDE ACTIVE INGREDIENTS AND PRODUCTS
# ============================================================================

INSECTICIDE_ACTIVE_INGREDIENTS = [
    {'name': 'Bifenthrin', 'chemical_family': 'Pyrethroid', 'mode_of_action': 'Sodium channel modulator', 'resistance_group': 'IRAC 3A'},
    {'name': 'Lambda-cyhalothrin', 'chemical_family': 'Pyrethroid', 'mode_of_action': 'Sodium channel modulator', 'resistance_group': 'IRAC 3A'},
    {'name': 'Gamma-cyhalothrin', 'chemical_family': 'Pyrethroid', 'mode_of_action': 'Sodium channel modulator', 'resistance_group': 'IRAC 3A'},
    {'name': 'Zeta-cypermethrin', 'chemical_family': 'Pyrethroid', 'mode_of_action': 'Sodium channel modulator', 'resistance_group': 'IRAC 3A'},
    {'name': 'Esfenvalerate', 'chemical_family': 'Pyrethroid', 'mode_of_action': 'Sodium channel modulator', 'resistance_group': 'IRAC 3A'},
    {'name': 'Chlorpyrifos', 'chemical_family': 'Organophosphate', 'mode_of_action': 'Acetylcholinesterase inhibitor', 'resistance_group': 'IRAC 1B'},
    {'name': 'Chlorantraniliprole', 'chemical_family': 'Diamide', 'mode_of_action': 'Ryanodine receptor modulator', 'resistance_group': 'IRAC 28'},
    {'name': 'Thiamethoxam', 'chemical_family': 'Neonicotinoid', 'mode_of_action': 'Nicotinic acetylcholine receptor agonist', 'resistance_group': 'IRAC 4A'},
    {'name': 'Imidacloprid', 'chemical_family': 'Neonicotinoid', 'mode_of_action': 'Nicotinic acetylcholine receptor agonist', 'resistance_group': 'IRAC 4A'},
    {'name': 'Acetamiprid', 'chemical_family': 'Neonicotinoid', 'mode_of_action': 'Nicotinic acetylcholine receptor agonist', 'resistance_group': 'IRAC 4A'},
    {'name': 'Methoxyfenozide', 'chemical_family': 'Diacylhydrazine', 'mode_of_action': 'Ecdysone receptor agonist', 'resistance_group': 'IRAC 18'},
    {'name': 'Carbaryl', 'chemical_family': 'Carbamate', 'mode_of_action': 'Acetylcholinesterase inhibitor', 'resistance_group': 'IRAC 1A'},
]

INSECTICIDE_PRODUCTS = [
    # Pyrethroids
    {
        'trade_name': 'Brigade 2EC',
        'manufacturer': 'FMC',
        'product_type': 'insecticide',
        'formulation': 'EC',
        'epa_reg_number': '279-3206',
        'active_ingredient': 'Bifenthrin',
        'concentration': '2 lb ai/gal',
        'corn_rate': '6.4 fl oz/acre',
        'soybean_rate': '6.4 fl oz/acre',
        'phi_days_corn': 30,
        'phi_days_soybean': 18,
        'rei_hours': 12,
        'targets': 'Armyworm, corn borer, corn rootworm adults, grasshoppers, bean leaf beetle, stink bugs',
        'timing': 'Apply when insects are small. Multiple applications may be needed.',
        'notes': 'Very broad spectrum. Pyrethroid resistance concerns. Good residual. Avoid drift to waterways.',
    },
    {
        'trade_name': 'Warrior II with Zeon Technology',
        'manufacturer': 'Syngenta',
        'product_type': 'insecticide',
        'formulation': 'CS',
        'epa_reg_number': '100-1519',
        'active_ingredient': 'Lambda-cyhalothrin',
        'concentration': '2.08 lb ai/gal',
        'corn_rate': '1.92-2.56 fl oz/acre',
        'soybean_rate': '1.92-2.56 fl oz/acre',
        'phi_days_corn': 30,
        'phi_days_soybean': 30,
        'rei_hours': 24,
        'targets': 'Armyworm, corn borer, corn earworm, cutworm, soybean aphid, bean leaf beetle, stink bugs',
        'timing': 'Apply when insects reach threshold. Repeat as needed.',
        'notes': 'Fast knockdown. Zeon technology provides longer residual. Excellent on aphids.',
    },
    {
        'trade_name': 'Mustang Maxx',
        'manufacturer': 'FMC',
        'product_type': 'insecticide',
        'formulation': 'EC',
        'epa_reg_number': '279-3426',
        'active_ingredient': 'Zeta-cypermethrin',
        'concentration': '0.8 lb ai/gal',
        'corn_rate': '2.8-4.0 fl oz/acre',
        'soybean_rate': '2.8-4.0 fl oz/acre',
        'phi_days_corn': 3,
        'phi_days_soybean': 1,
        'rei_hours': 12,
        'targets': 'Armyworm, corn borer, grasshoppers, soybean aphid, bean leaf beetle, stink bugs',
        'timing': 'Apply when insects are present. Multiple applications if needed.',
        'notes': 'Short PHI. Good fit for late season applications. Effective on aphids.',
    },
    {
        'trade_name': 'Asana XL',
        'manufacturer': 'UPL',
        'product_type': 'insecticide',
        'formulation': 'EC',
        'epa_reg_number': '66222-147',
        'active_ingredient': 'Esfenvalerate',
        'concentration': '0.66 lb ai/gal',
        'corn_rate': '5.8-9.6 fl oz/acre',
        'soybean_rate': '5.8-9.6 fl oz/acre',
        'phi_days_corn': 21,
        'phi_days_soybean': 21,
        'rei_hours': 12,
        'targets': 'Armyworm, corn borer, corn earworm, grasshoppers, bean leaf beetle',
        'timing': 'Apply when insects are actively feeding.',
        'notes': 'Good broad spectrum activity. Lower environmental impact than some pyrethroids.',
    },

    # Organophosphates
    {
        'trade_name': 'Lorsban Advanced',
        'manufacturer': 'Corteva',
        'product_type': 'insecticide',
        'formulation': 'EC',
        'epa_reg_number': '62719-591',
        'active_ingredient': 'Chlorpyrifos',
        'concentration': '4 lb ai/gal',
        'corn_rate': '1-2 pt/acre',
        'soybean_rate': '1-2 pt/acre',
        'phi_days_corn': 35,
        'phi_days_soybean': 28,
        'rei_hours': 24,
        'targets': 'Corn rootworm, cutworm, armyworm, corn borer, soybean aphid (suppression)',
        'timing': 'At-plant soil application for rootworm. Foliar for cutworms and borers.',
        'notes': 'Being phased out. Check current registration status. Different MOA than pyrethroids for resistance management.',
    },

    # Diamides
    {
        'trade_name': 'Besiege',
        'manufacturer': 'Syngenta',
        'product_type': 'insecticide',
        'formulation': 'SC',
        'epa_reg_number': '100-1523',
        'active_ingredient': 'Chlorantraniliprole + Lambda-cyhalothrin',
        'concentration': 'Group 28 + Group 3A',
        'corn_rate': '6-9 fl oz/acre',
        'soybean_rate': '6-9 fl oz/acre',
        'phi_days_corn': 30,
        'phi_days_soybean': 30,
        'rei_hours': 24,
        'targets': 'Armyworm, western bean cutworm, corn earworm, stink bugs, bean leaf beetle',
        'timing': 'Apply when insects are small.',
        'notes': 'Excellent for caterpillars. Combines fast knockdown (pyrethroid) with residual (diamide). Premium pricing.',
    },
    {
        'trade_name': 'Coragen',
        'manufacturer': 'FMC',
        'product_type': 'insecticide',
        'formulation': 'SC',
        'epa_reg_number': '279-3426',
        'active_ingredient': 'Chlorantraniliprole',
        'concentration': '1.67 lb ai/gal',
        'corn_rate': '3.5-7.5 fl oz/acre',
        'soybean_rate': '3.5-7.5 fl oz/acre',
        'phi_days_corn': 1,
        'phi_days_soybean': 1,
        'rei_hours': 4,
        'targets': 'Armyworm, western bean cutworm, corn borer, loopers',
        'timing': 'Apply at egg hatch or when larvae are small.',
        'notes': 'Excellent on caterpillars. Long residual. Low mammalian toxicity. Very short PHI and REI.',
    },

    # Neonicotinoids
    {
        'trade_name': 'Actara',
        'manufacturer': 'Syngenta',
        'product_type': 'insecticide',
        'formulation': 'WDG',
        'epa_reg_number': '100-1443',
        'active_ingredient': 'Thiamethoxam',
        'concentration': '25% WDG',
        'corn_rate': '3.0-4.0 oz/acre',
        'soybean_rate': '2.0-5.5 oz/acre',
        'phi_days_corn': 21,
        'phi_days_soybean': 21,
        'rei_hours': 12,
        'targets': 'Soybean aphid, bean leaf beetle, Japanese beetle, stink bugs',
        'timing': 'Apply when insects reach threshold.',
        'notes': 'Excellent on sucking insects. Good on aphids. Longer residual than pyrethroids on aphids.',
    },
    {
        'trade_name': 'Assail 30SG',
        'manufacturer': 'UPL',
        'product_type': 'insecticide',
        'formulation': 'SG',
        'epa_reg_number': '66222-162',
        'active_ingredient': 'Acetamiprid',
        'concentration': '30% SG',
        'corn_rate': '2.0-5.3 oz/acre',
        'soybean_rate': '1.5-4.0 oz/acre',
        'phi_days_corn': 7,
        'phi_days_soybean': 7,
        'rei_hours': 12,
        'targets': 'Soybean aphid, stink bugs, bean leaf beetle',
        'timing': 'Apply when aphids reach threshold.',
        'notes': 'Good aphid control. Better stink bug activity than some neonics. Short PHI.',
    },

    # Growth Regulators
    {
        'trade_name': 'Intrepid 2F',
        'manufacturer': 'Valent',
        'product_type': 'insecticide',
        'formulation': 'F',
        'epa_reg_number': '59639-99',
        'active_ingredient': 'Methoxyfenozide',
        'concentration': '2 lb ai/gal',
        'corn_rate': '4-10 fl oz/acre',
        'soybean_rate': '4-10 fl oz/acre',
        'phi_days_corn': 7,
        'phi_days_soybean': 7,
        'rei_hours': 4,
        'targets': 'Armyworm, corn borer, loopers, green cloverworm',
        'timing': 'Apply when larvae are small.',
        'notes': 'Selective for caterpillars. Preserves beneficials. Different MOA for resistance management.',
    },

    # Carbamates
    {
        'trade_name': 'Sevin XLR Plus',
        'manufacturer': 'Bayer',
        'product_type': 'insecticide',
        'formulation': 'F',
        'epa_reg_number': '264-625',
        'active_ingredient': 'Carbaryl',
        'concentration': '4 lb ai/gal',
        'corn_rate': '1-2 qt/acre',
        'soybean_rate': '0.5-2 qt/acre',
        'phi_days_corn': 0,
        'phi_days_soybean': 3,
        'rei_hours': 12,
        'targets': 'Grasshoppers, corn earworm, Japanese beetle, armyworm',
        'timing': 'Apply when insects are present.',
        'notes': 'Very broad spectrum. Good on grasshoppers. Zero PHI on corn. Can harm beneficials.',
    },
]

# ============================================================================
# FUNGICIDE ACTIVE INGREDIENTS AND PRODUCTS
# ============================================================================

FUNGICIDE_ACTIVE_INGREDIENTS = [
    {'name': 'Azoxystrobin', 'chemical_family': 'Strobilurin (QoI)', 'mode_of_action': 'Complex III inhibitor', 'resistance_group': 'FRAC 11'},
    {'name': 'Pyraclostrobin', 'chemical_family': 'Strobilurin (QoI)', 'mode_of_action': 'Complex III inhibitor', 'resistance_group': 'FRAC 11'},
    {'name': 'Trifloxystrobin', 'chemical_family': 'Strobilurin (QoI)', 'mode_of_action': 'Complex III inhibitor', 'resistance_group': 'FRAC 11'},
    {'name': 'Propiconazole', 'chemical_family': 'Triazole (DMI)', 'mode_of_action': 'Sterol biosynthesis inhibitor', 'resistance_group': 'FRAC 3'},
    {'name': 'Prothioconazole', 'chemical_family': 'Triazole (DMI)', 'mode_of_action': 'Sterol biosynthesis inhibitor', 'resistance_group': 'FRAC 3'},
    {'name': 'Tebuconazole', 'chemical_family': 'Triazole (DMI)', 'mode_of_action': 'Sterol biosynthesis inhibitor', 'resistance_group': 'FRAC 3'},
    {'name': 'Mefenoxam', 'chemical_family': 'Phenylamide', 'mode_of_action': 'RNA polymerase I inhibitor', 'resistance_group': 'FRAC 4'},
    {'name': 'Fluopyram', 'chemical_family': 'Pyridinyl-ethyl-benzamide', 'mode_of_action': 'Complex II inhibitor', 'resistance_group': 'FRAC 7'},
]

FUNGICIDE_PRODUCTS = [
    # Strobilurin + Triazole Premixes (Most Common)
    {
        'trade_name': 'Trivapro',
        'manufacturer': 'Syngenta',
        'product_type': 'fungicide',
        'formulation': 'A',
        'epa_reg_number': '100-1642',
        'active_ingredient': 'Azoxystrobin + Propiconazole + Benzovindiflupyr',
        'concentration': 'Group 11 + Group 3 + Group 7',
        'corn_rate': '13.7 fl oz/acre',
        'soybean_rate': '13.7 fl oz/acre',
        'phi_days_corn': 30,
        'phi_days_soybean': 21,
        'rei_hours': 12,
        'targets_corn': 'Gray leaf spot, northern corn leaf blight, southern rust, tar spot, anthracnose',
        'targets_soybean': 'Frogeye leaf spot, septoria brown spot, cercospora leaf blight, anthracnose',
        'timing': 'VT-R2 for corn. R3-R4 for soybeans. Preventive to early disease.',
        'notes': 'Premium three-way mix. Excellent activity on most diseases. Good for tar spot.',
    },
    {
        'trade_name': 'Delaro 325 SC',
        'manufacturer': 'Bayer',
        'product_type': 'fungicide',
        'formulation': 'SC',
        'epa_reg_number': '264-1050',
        'active_ingredient': 'Prothioconazole + Trifloxystrobin',
        'concentration': 'Group 3 + Group 11',
        'corn_rate': '8 fl oz/acre',
        'soybean_rate': '8 fl oz/acre',
        'phi_days_corn': 30,
        'phi_days_soybean': 30,
        'rei_hours': 12,
        'targets_corn': 'Gray leaf spot, northern corn leaf blight, common rust, eyespot',
        'targets_soybean': 'Frogeye leaf spot, septoria brown spot, cercospora leaf blight',
        'timing': 'V5-R2 for corn. R3-R5 for soybeans.',
        'notes': 'Strong on leaf spots. Prothio is very effective triazole. Premium pricing.',
    },
    {
        'trade_name': 'Priaxor',
        'manufacturer': 'BASF',
        'product_type': 'fungicide',
        'formulation': 'EC',
        'epa_reg_number': '7969-338',
        'active_ingredient': 'Pyraclostrobin + Fluxapyroxad',
        'concentration': 'Group 11 + Group 7',
        'corn_rate': '4-8 fl oz/acre',
        'soybean_rate': '4-8 fl oz/acre',
        'phi_days_corn': 7,
        'phi_days_soybean': 14,
        'rei_hours': 12,
        'targets_corn': 'Gray leaf spot, northern corn leaf blight, southern corn leaf blight, common rust, tar spot',
        'targets_soybean': 'Frogeye leaf spot, cercospora leaf blight, white mold (suppression)',
        'timing': 'VT-R2 for corn. R3-R5 for soybeans.',
        'notes': 'Excellent on gray leaf spot. White mold suppression in soybeans. Short PHI.',
    },
    {
        'trade_name': 'Stratego YLD',
        'manufacturer': 'Bayer',
        'product_type': 'fungicide',
        'formulation': 'EC',
        'epa_reg_number': '264-826',
        'active_ingredient': 'Prothioconazole + Trifloxystrobin',
        'concentration': 'Group 3 + Group 11',
        'corn_rate': '4 fl oz/acre',
        'soybean_rate': '4 fl oz/acre',
        'phi_days_corn': 30,
        'phi_days_soybean': 30,
        'rei_hours': 12,
        'targets_corn': 'Gray leaf spot, northern corn leaf blight, common rust, southern rust',
        'targets_soybean': 'Frogeye leaf spot, septoria brown spot, anthracnose',
        'timing': 'V5-R2 for corn. R3-R5 for soybeans.',
        'notes': 'Cost-effective option. Good broad-spectrum activity.',
    },
    {
        'trade_name': 'Quadris',
        'manufacturer': 'Syngenta',
        'product_type': 'fungicide',
        'formulation': 'SC',
        'epa_reg_number': '100-813',
        'active_ingredient': 'Azoxystrobin',
        'concentration': '2.08 lb ai/gal - Group 11',
        'corn_rate': '6.0-12.5 fl oz/acre',
        'soybean_rate': '6.0-15.4 fl oz/acre',
        'phi_days_corn': 14,
        'phi_days_soybean': 14,
        'rei_hours': 4,
        'targets_corn': 'Gray leaf spot, northern corn leaf blight, common rust',
        'targets_soybean': 'Frogeye leaf spot, septoria brown spot',
        'timing': 'VT-R1 for corn. R3-R5 for soybeans.',
        'notes': 'Single-mode fungicide. Must tank mix triazole for resistance management. Good option for cost-conscious applications.',
    },

    # White Mold Specific
    {
        'trade_name': 'Endura',
        'manufacturer': 'Valent',
        'product_type': 'fungicide',
        'formulation': 'WDG',
        'epa_reg_number': '59639-97',
        'active_ingredient': 'Boscalid',
        'concentration': '70% WDG - Group 7',
        'corn_rate': 'Not labeled',
        'soybean_rate': '6.5-11 oz/acre',
        'phi_days_corn': None,
        'phi_days_soybean': 30,
        'rei_hours': 12,
        'targets_corn': None,
        'targets_soybean': 'White mold (Sclerotinia)',
        'timing': 'R1-R2 in white mold high-risk situations.',
        'notes': 'Specifically for white mold. Expensive. Variable efficacy. Best with good coverage.',
    },
    {
        'trade_name': 'Proline 480 SC',
        'manufacturer': 'Bayer',
        'product_type': 'fungicide',
        'formulation': 'SC',
        'epa_reg_number': '264-1155',
        'active_ingredient': 'Prothioconazole',
        'concentration': '41% - Group 3',
        'corn_rate': 'Not labeled',
        'soybean_rate': '5.7 fl oz/acre',
        'phi_days_corn': None,
        'phi_days_soybean': 30,
        'rei_hours': 12,
        'targets_corn': None,
        'targets_soybean': 'White mold, frogeye leaf spot, cercospora leaf blight',
        'timing': 'R1-R3 for white mold. R3-R5 for foliar diseases.',
        'notes': 'Good white mold activity. Can be tank-mixed with strobilurins. Premium triazole.',
    },

    # Seed Treatment Fungicides
    {
        'trade_name': 'ILeVO',
        'manufacturer': 'Bayer',
        'product_type': 'fungicide',
        'formulation': 'FS',
        'epa_reg_number': '264-1155',
        'active_ingredient': 'Fluopyram',
        'concentration': 'Group 7',
        'corn_rate': None,
        'soybean_rate': 'Seed treatment only',
        'phi_days_corn': None,
        'phi_days_soybean': None,
        'rei_hours': None,
        'targets_corn': None,
        'targets_soybean': 'Sudden death syndrome (SDS), Seedling diseases',
        'timing': 'Applied as seed treatment before planting.',
        'notes': 'Only seed treatment proven to reduce SDS. Critical in high-SDS fields. Premium seed treatment.',
    },
    {
        'trade_name': 'ApronMaxx RFC',
        'manufacturer': 'Syngenta',
        'product_type': 'fungicide',
        'formulation': 'FS',
        'epa_reg_number': '100-1090',
        'active_ingredient': 'Mefenoxam + Fludioxonil',
        'concentration': 'Group 4 + Group 12',
        'corn_rate': 'Seed treatment',
        'soybean_rate': 'Seed treatment',
        'phi_days_corn': None,
        'phi_days_soybean': None,
        'rei_hours': None,
        'targets_corn': 'Pythium, Fusarium, Rhizoctonia',
        'targets_soybean': 'Pythium, Phytophthora (races), Fusarium, Rhizoctonia',
        'timing': 'Applied as seed treatment before planting.',
        'notes': 'Standard seed treatment. Mefenoxam for Pythium/Phytophthora, fludioxonil for Fusarium/Rhizoctonia.',
    },
]

# ============================================================================
# ADJUVANTS AND SPRAY ADDITIVES
# ============================================================================

ADJUVANTS = [
    {
        'trade_name': 'Induce',
        'manufacturer': 'Helena',
        'product_type': 'adjuvant',
        'adjuvant_type': 'NIS (Non-ionic surfactant)',
        'rate': '0.25% v/v (2 pts/100 gal)',
        'use_with': 'Most herbicides and insecticides',
        'notes': 'General purpose surfactant. Improves coverage and penetration.',
    },
    {
        'trade_name': 'Preference',
        'manufacturer': 'Winfield United',
        'product_type': 'adjuvant',
        'adjuvant_type': 'MSO (Methylated seed oil)',
        'rate': '1% v/v',
        'use_with': 'Herbicides, some insecticides and fungicides',
        'notes': 'Better leaf penetration than NIS. Often used with residual herbicides.',
    },
    {
        'trade_name': 'Dyne-Amic',
        'manufacturer': 'Helena',
        'product_type': 'adjuvant',
        'adjuvant_type': 'MSO',
        'rate': '1% v/v',
        'use_with': 'Herbicides',
        'notes': 'Methylated seed oil with emulsifiers.',
    },
    {
        'trade_name': 'InterLock',
        'manufacturer': 'Winfield United',
        'product_type': 'adjuvant',
        'adjuvant_type': 'Deposition aid',
        'rate': '3-6 fl oz/acre',
        'use_with': 'Fungicides, insecticides, herbicides',
        'notes': 'Improves coverage and rainfastness. Good for fungicides.',
    },
]

# ============================================================================
# ECONOMIC THRESHOLDS AND RESISTANCE MANAGEMENT
# ============================================================================

ECONOMIC_THRESHOLDS_DETAIL = {
    'corn_rootworm_adult': {
        'threshold': '1 beetle/plant during silking',
        'scouting_method': 'Count beetles on 10 consecutive plants in 5 locations',
        'timing': 'During silking (R1)',
        'action': 'Consider foliar insecticide if silk clipping threatens pollination',
        'notes': 'Rarely economic in grain corn. More important in seed production.',
    },
    'european_corn_borer': {
        'threshold': '50% plants with egg masses or larvae before tassel',
        'scouting_method': 'Check whorl of 20 plants in 5 locations',
        'timing': 'Late whorl to pre-tassel',
        'action': 'Apply pyrethroid or Bt when threshold reached',
        'notes': 'Timing critical - treat at 5-10% tassel for 2nd generation',
    },
    'western_bean_cutworm': {
        'threshold': '5% plants with egg masses or 8% with larvae in silks',
        'scouting_method': 'Check upper leaves for eggs, silks for larvae',
        'timing': 'Late whorl through early silk',
        'action': 'Foliar insecticide at egg hatch',
        'notes': 'Time application 5-7 days after peak moth flight',
    },
    'fall_armyworm': {
        'threshold': '25% plants with whorl damage before V6',
        'scouting_method': 'Check whorl of 20 plants in 5 locations',
        'timing': 'V3-V6',
        'action': 'Foliar insecticide when threshold reached',
        'notes': 'Treat when larvae still small for best control',
    },
    'soybean_aphid': {
        'threshold': '250 aphids/plant with population increasing',
        'scouting_method': 'Count aphids on 20-30 plants across field',
        'timing': 'V2 through R5',
        'action': 'Apply foliar insecticide',
        'notes': 'Do not treat after R6. Scout twice weekly when populations building.',
    },
    'bean_leaf_beetle_defoliation': {
        'threshold': '20% defoliation before R6 and beetles active',
        'scouting_method': 'Estimate defoliation on 20 plants',
        'timing': 'Vegetative through R5',
        'action': 'Apply foliar insecticide',
        'notes': 'Consider virus transmission in early season',
    },
    'bean_leaf_beetle_pod_feeding': {
        'threshold': '10-15% pod injury',
        'scouting_method': 'Check 20 plants in 5 locations for pod scarring',
        'timing': 'R4-R6',
        'action': 'Apply foliar insecticide',
        'notes': 'Pod feeding has greater yield impact than defoliation',
    },
    'japanese_beetle': {
        'threshold': '30% defoliation before R1, 20% after R1',
        'scouting_method': 'Estimate defoliation on 20 plants',
        'timing': 'Late June through August',
        'action': 'Apply foliar insecticide',
        'notes': 'Often concentrated on field edges',
    },
    'spider_mites_corn': {
        'threshold': '20-25% leaf area damaged before dent',
        'scouting_method': 'Check lower leaves for stippling and mites',
        'timing': 'Mid-season through grain fill',
        'action': 'Apply miticide if spreading',
        'notes': 'Usually field edges. Worse in drought. Avoid pyrethroids.',
    },
    'spider_mites_soybean': {
        'threshold': '20% of plants with mites and stippling',
        'scouting_method': 'Check lower leaves for stippling, shake over white paper',
        'timing': 'Mid-season through R5',
        'action': 'Apply miticide when actively spreading',
        'notes': 'Populations explode in hot, dry weather. Act quickly.',
    },
    'stink_bugs': {
        'threshold': '5-10 stink bugs per 25 sweeps during pod fill',
        'scouting_method': 'Sweep net - 25 sweeps in 4-5 locations',
        'timing': 'R3 through R6',
        'action': 'Apply foliar insecticide',
        'notes': 'Difficult to control in dense canopy. May need repeat application.',
    },
}

RESISTANCE_MANAGEMENT_STRATEGIES = {
    'pyrethroid_resistance': {
        'concern': 'Widespread resistance in corn rootworm beetles, some aphids',
        'strategy': 'Rotate to different MOA. Use organophosphates, diamides, or neonicotinoids.',
        'notes': 'Avoid using pyrethroids exclusively. Tank mix with different MOA when possible.',
    },
    'fungicide_resistance': {
        'concern': 'QoI (strobilurin) resistance documented in some diseases',
        'strategy': 'Always tank mix or use premix with triazole (Group 3). Rotate MOAs season to season.',
        'notes': 'Do not use single-mode fungicides (QoI alone). Premixes strongly preferred.',
    },
    'neonicotinoid_resistance': {
        'concern': 'Some soybean aphid populations showing reduced susceptibility',
        'strategy': 'Rotate with pyrethroids, organophosphates. Scout after treatment to verify control.',
        'notes': 'Resistance still uncommon but emerging. Monitor for control failures.',
    },
}

# This data will be used to populate the chemical database with real-world product information
