"""
Professional Crop Consulting System - Knowledge Base Seeding
Corn and Soybean Pest/Disease Database with Real-World Consulting Data
"""

# ============================================================================
# CORN AND SOYBEAN PEST DATABASE
# Based on Extension Publications and 30 Years of Field Experience
# ============================================================================

CORN_PESTS = [
    {
        'common_name': 'Corn Rootworm (Western and Northern)',
        'scientific_name': 'Diabrotica virgifera (Western), D. barberi (Northern)',
        'pest_type': 'insect',
        'description': 'Most economically damaging corn pest in North America. Larvae feed on roots causing lodging and yield loss. Adults feed on silks interfering with pollination.',
        'lifecycle': 'One generation per year. Eggs overwinter in soil, larvae hatch and feed on roots in May-June, adults emerge in July-August.',
        'identification_features': 'Adults: 1/4 inch beetles. Western is yellow-green with three black stripes, Northern is tan. Larvae: white worms with brown head capsule up to 1/2 inch long.',
        'damage_symptoms': 'Root pruning (goose-necking), lodging, stunted plants, nutrient/water stress. Adult feeding on silks can reduce pollination.',
        'economic_threshold': 'Larvae: Node injury score of 0.75+ (Iowa scale). Adults: 1+ beetle per plant during silking or 2+ beetles per plant pre-silk in seed corn',
        'management_notes': 'Crop rotation is most effective. Bt corn hybrids. Soil-applied insecticides at planting. Adult foliar sprays only if silk clipping threatens pollination.',
    },
    {
        'common_name': 'European Corn Borer',
        'scientific_name': 'Ostrinia nubilalis',
        'pest_type': 'insect',
        'description': 'Major pest causing stalk breakage and direct ear damage. First generation feeds on whorl, second generation tunnels in stalks and ears.',
        'lifecycle': '1-3 generations per year depending on latitude. Overwinters as mature larvae in corn stubble. Adults emerge May-June (1st gen) and July-August (2nd gen).',
        'identification_features': 'Larvae: Flesh-colored caterpillar with dark spots, up to 1 inch. Adults: Tan moths with wavy darker bands, 1 inch wingspan. Look for "shothole" damage in whorl.',
        'damage_symptoms': 'First gen: shothole feeding in whorl, broken tassels. Second gen: stalk tunneling causing breakage, direct ear feeding, dropped ears.',
        'economic_threshold': '50% of plants with egg masses or larvae (pre-tassel). 1+ larvae per plant in late whorl stage.',
        'management_notes': 'Bt corn highly effective. Foliar pyrethroids when eggs hatch. Timing critical - spray at 5-10% tassel for second generation.',
    },
    {
        'common_name': 'Western Bean Cutworm',
        'scientific_name': 'Striacosta albicosta',
        'pest_type': 'insect',
        'description': 'Increasingly important pest that feeds directly on developing kernels, causing high-value damage and promoting ear mold.',
        'lifecycle': 'One generation per year. Overwinters as prepupa in soil. Adults emerge late June-July. Eggs laid on upper leaf surface.',
        'identification_features': 'Larvae: Light tan/pink with dark spots forming bands, up to 1.5 inches. Adults: Tan moths with white kidney-shaped spot on forewing.',
        'damage_symptoms': 'Larva tunnels into ear tip through husk, feeds on kernels. Opens pathway for diseases. Multiple larvae per ear common.',
        'economic_threshold': '5% of pre-tassel plants with egg masses or 8% of plants with fresh larvae in silks',
        'management_notes': 'Scout for eggs on upper leaves. Foliar insecticides at egg hatch (5-7 days after peak moth flight). Some Bt traits provide partial control.',
    },
    {
        'common_name': 'Fall Armyworm',
        'scientific_name': 'Spodoptera frugiperda',
        'pest_type': 'insect',
        'description': 'Highly mobile defoliator that can cause severe damage in late-planted or late-season corn. Migrates north annually.',
        'lifecycle': 'Does not overwinter in northern states. Multiple generations in South, migrants arrive June-July in Corn Belt.',
        'identification_features': 'Larvae: Green to brown with distinctive inverted white "Y" on head. Three white stripes down back. Up to 1.5 inches.',
        'damage_symptoms': 'Whorl feeding, ragged leaves, frass in whorl. Can cause complete defoliation in severe cases.',
        'economic_threshold': '25% of plants with whorl damage before V6 stage',
        'management_notes': 'Foliar insecticides when larvae small. Scout frequently during migration periods. Bt corn provides control.',
    },
    {
        'common_name': 'Black Cutworm',
        'scientific_name': 'Agrotis ipsilon',
        'pest_type': 'insect',
        'description': 'Early season pest that cuts plants at or below soil line. Most damage in weedy fields or after cover crops.',
        'lifecycle': 'Does not overwinter north. Adults migrate in spring. Eggs laid on early vegetation.',
        'identification_features': 'Larvae: Greasy-gray to black cutworms, curl when disturbed. Up to 1.5-2 inches. Hide in soil during day.',
        'damage_symptoms': 'Plants cut at or below soil line. Leaf feeding on small plants. Stand loss. Wilted or missing plants.',
        'economic_threshold': '2-3% plants cut before V5, or 5-7% plants with leaf feeding',
        'management_notes': 'Scout after moth flights. Rescue treatment with pyrethroids. Bt seed treatments less effective against cutworms.',
    },
    {
        'common_name': 'Corn Leaf Aphid',
        'scientific_name': 'Rhopalosiphum maidis',
        'pest_type': 'insect',
        'description': 'Small sucking insect that colonizes whorl and tassel. Can vector viruses. Most common in stressed conditions.',
        'lifecycle': 'Multiple generations per season. Wingless and winged forms. Populations peak during tassel/silk.',
        'identification_features': 'Small (1/16 inch) blue-green aphids with dark legs. Colonies in whorl and on tassel. Sticky honeydew visible.',
        'damage_symptoms': 'Usually minimal direct damage. Heavy infestations can cause stunting, poor pollination. More concern for virus transmission.',
        'economic_threshold': '50% of plants with moderate to heavy colonization in whorl or 50% of pre-tassel plants with aphids in whorls',
        'management_notes': 'Natural enemies usually provide control. Foliar insecticides rarely economical except in seed production.',
    },
    {
        'common_name': 'Spider Mites (Two-spotted)',
        'scientific_name': 'Tetranychus urticae',
        'pest_type': 'mite',
        'description': 'Hot, dry weather pest that can cause rapid defoliation. Most severe on drought-stressed corn and field edges.',
        'lifecycle': 'Multiple generations per year (5-7 days generation time in hot weather). Overwinter as adults.',
        'identification_features': 'Tiny (1/50 inch) eight-legged mites, cream to greenish with two dark spots. Look for webbing on leaves. Stippling on lower leaf surface.',
        'damage_symptoms': 'Yellow stippling on leaves, progressing to bronze/brown appearance. Webbing. Premature leaf death. Most severe below ear.',
        'economic_threshold': '20-25% of leaf area damaged before dent stage',
        'management_notes': 'Usually limited to field edges. Miticides may be needed in drought years. Avoid pyrethroids which flare mites. Irrigation helps.',
    },
    {
        'common_name': 'Japanese Beetle',
        'scientific_name': 'Popillia japonica',
        'pest_type': 'insect',
        'description': 'Adult beetles feed on corn silks and leaves. Can interfere with pollination in severe infestations.',
        'lifecycle': 'One generation per year. Larvae (grubs) develop in soil. Adults emerge late June-July for 4-6 weeks.',
        'identification_features': 'Adults: 3/8 inch metallic green beetles with bronze wing covers. White tufts of hair along sides.',
        'damage_symptoms': 'Silk clipping during pollination. Leaf skeletonizing. Usually scattered distribution but can aggregate.',
        'economic_threshold': '3+ beetles per ear during silking in seed corn; rarely economic in grain corn',
        'management_notes': 'Usually not economically damaging in grain corn. Monitor during pollination. Foliar pyrethroids if needed.',
    },
    {
        'common_name': 'Stalk Borer',
        'scientific_name': 'Papaipema nebris',
        'pest_type': 'insect',
        'description': 'Early season pest that tunnels into corn stalks causing "dead heart". Most common near grassy field edges.',
        'lifecycle': 'One generation per year. Overwinters as eggs on grasses. Larvae bore into corn in May-June.',
        'identification_features': 'Larvae: Purple/brown striped with white stripes. Migrates from grass into corn at V4-V6.',
        'damage_symptoms': 'Dead whorl (dead heart), stunted plants, stem tunneling. Usually confined to field edges near grassy areas.',
        'economic_threshold': 'No established threshold. Damage usually too sporadic for foliar treatment.',
        'management_notes': 'Control grassy weeds in borders. Usually not economic to spray field. May treat field edges preventively.',
    },
    {
        'common_name': 'Corn Earworm / Soybean Podworm',
        'scientific_name': 'Helicoverpa zea',
        'pest_type': 'insect',
        'description': 'Feeds on corn ears and soybean pods. Major pest in seed production and southern regions.',
        'lifecycle': 'Multiple generations, migrates north. Does not survive northern winters.',
        'identification_features': 'Larvae: Variable color (green, pink, brown) with longitudinal stripes. Up to 2 inches. One larva per ear/pod cluster typical.',
        'damage_symptoms': 'Corn: kernel feeding at ear tip. Soybeans: pod feeding, entry holes in pods.',
        'economic_threshold': 'Field corn: rarely economic. Seed corn: 5-10% infested silks. Soybeans: 20-25% of plants with larvae in reproductive stages',
        'management_notes': 'Bt corn effective. Difficult to control in soybeans due to pod protection. Time sprays for egg hatch.',
    }
]

SOYBEAN_PESTS = [
    {
        'common_name': 'Soybean Aphid',
        'scientific_name': 'Aphis glycines',
        'pest_type': 'insect',
        'description': 'Most economically important soybean pest in North-Central US. Can cause severe yield loss and spread viruses.',
        'lifecycle': 'Multiple generations per year (asexual). Overwinters on buckthorn. Colonizes soybeans V1-V3, populations peak R1-R5.',
        'identification_features': 'Small (1/16 inch) yellow aphids with black cornicles. Both winged and wingless forms. Colonies on undersides of leaves and stems.',
        'damage_symptoms': 'Curled, distorted leaves. Stunting. Honeydew and sooty mold. Yield loss from sucking damage. Premature plant death in severe cases.',
        'economic_threshold': '250 aphids per plant with increasing populations before R6',
        'management_notes': 'Scout weekly V2-R5. Foliar insecticides (pyrethroids, organophosphates) when threshold exceeded. Consider resistant varieties.',
    },
    {
        'common_name': 'Two-Spotted Spider Mite',
        'scientific_name': 'Tetranychus urticae',
        'pest_type': 'mite',
        'description': 'Hot, dry weather pest that can cause rapid yield loss in soybeans. Often starts on field edges.',
        'lifecycle': 'Multiple generations (5-7 days in hot weather). Populations explode during drought.',
        'identification_features': 'Tiny (1/50 inch) eight-legged mites. Cream to green with two dark spots. Heavy webbing on plants. Stippling on leaves.',
        'damage_symptoms': 'Yellow stippling on lower leaves, progressing upward. Bronze/brown leaves. Webbing between leaves. Premature defoliation.',
        'economic_threshold': '10-20% defoliation before R5, or 25-30% after R5',
        'management_notes': 'Requires miticides, not insecticides. Avoid pyrethroids which kill predators. Treat when active mites present with symptoms spreading.',
    },
    {
        'common_name': 'Bean Leaf Beetle',
        'scientific_name': 'Cerotoma trifurcata',
        'pest_type': 'insect',
        'description': 'Common defoliator and pod feeder. Also vectors bean pod mottle virus. Two generations per year.',
        'lifecycle': 'Overwinters as adult. First generation emerges at soybean emergence, second generation in mid-late summer.',
        'identification_features': 'Adults: 1/4 inch beetle, variable color (red, yellow, tan) with black triangle behind head. May have 4 spots. Larvae in soil on roots.',
        'damage_symptoms': 'Defoliation (round holes). Pod feeding in fall. Early-season stand reduction. Round or irregular holes in leaves.',
        'economic_threshold': 'Seedling: 50% defoliation before V3. Vegetative: rarely economic. Reproductive: 20% defoliation before R6 or 10-15% pod injury',
        'management_notes': 'Usually not economic to spray except at seedling or heavy pod feeding. Pyrethroids effective. Consider virus transmission risk.',
    },
    {
        'common_name': 'Japanese Beetle',
        'scientific_name': 'Popillia japonica',
        'pest_type': 'insect',
        'description': 'Can cause severe defoliation, especially on field edges. Adults aggregate in patches.',
        'lifecycle': 'One generation per year. Larvae (grubs) in soil. Adults emerge late June-early August.',
        'identification_features': 'Adults: 3/8-1/2 inch metallic green with bronze wing covers. White tufts along sides and back.',
        'damage_symptoms': 'Leaf skeletonizing between veins. Can cause severe defoliation. Usually patchy distribution.',
        'economic_threshold': '30% defoliation before bloom (R1), 20% defoliation from bloom to pod fill (R1-R5)',
        'management_notes': 'Often confined to field edges. Foliar pyrethroids or organophosphates. Check for lady beetle larvae before spraying.',
    },
    {
        'common_name': 'Grasshoppers',
        'scientific_name': 'Multiple species',
        'pest_type': 'insect',
        'description': 'Hot, dry weather pest. Most damaging when moving from drying small grains or roadsides into soybeans.',
        'lifecycle': 'One generation per year. Eggs overwinter in soil. Nymphs emerge May-June, adults present July-September.',
        'identification_features': 'Various sizes and colors. Look for chewing damage and presence of hoppers. Most species 1-2 inches as adults.',
        'damage_symptoms': 'Ragged leaf edges, defoliation. Nymphs on lower canopy, adults throughout. Often invade from field margins.',
        'economic_threshold': '40% defoliation before bloom, 20% defoliation from bloom to pod fill',
        'management_notes': 'Treat field margins first. Pyrethroids or carbaryl. More common in droughty years.',
    },
    {
        'common_name': 'Stink Bugs (Brown Marmorated, Green, Brown)',
        'scientific_name': 'Halyomorpha halys, Chinavia hilaris, Euschistus servus',
        'pest_type': 'insect',
        'description': 'Piercing-sucking pests that feed on developing seeds causing yield and quality loss. Increasingly important.',
        'lifecycle': '1-2 generations per year. Overwinter as adults (BMSB in structures). Move into soybeans during pod development.',
        'identification_features': 'Shield-shaped bugs, 1/2-3/4 inch. Green stink bug is bright green. Brown marmorated has white bands on antennae and legs.',
        'damage_symptoms': 'Pod feeding causes flat, shriveled seeds. Delayed maturity. Green stem disorder. Difficult to scout (hide in canopy).',
        'economic_threshold': '5-10 stink bugs per 25 sweeps during pod fill (R3-R6)',
        'management_notes': 'Difficult to control in dense canopy. Pyrethroids or neonicotinoids. Multiple applications may be needed. Focus R3-R5.',
    },
    {
        'common_name': 'Dectes Stem Borer',
        'scientific_name': 'Dectes texanus',
        'pest_type': 'insect',
        'description': 'Beetle that tunnels in soybean stems causing lodging. Larvae girdle stems internally causing late-season lodging.',
        'lifecycle': 'One generation per year. Overwinters as larva in stem. Adults emerge July-August.',
        'identification_features': 'Adults: Small (1/4 inch) gray long-horned beetle. Larvae: White, legless grub inside stem. Look for girdle just above soil.',
        'damage_symptoms': 'Tunneling in upper stem and petioles. Internal girdling causes late-season lodging. Reduced harvest efficiency.',
        'economic_threshold': 'No economic threshold established. Foliar treatments generally ineffective.',
        'management_notes': 'Limited management options. Early harvest and tillage to destroy residue. Avoid susceptible varieties in high-pressure areas.',
    },
    {
        'common_name': 'Soybean Looper',
        'scientific_name': 'Chrysodeixis includens',
        'pest_type': 'insect',
        'description': 'Defoliator most common in southern US, occasional migrant to Midwest. Distinctive looping movement.',
        'lifecycle': 'Does not survive northern winters. Multiple generations in South, migrants arrive July-August.',
        'identification_features': 'Larvae: Green caterpillar with white stripes, moves in looping motion, 1-1.5 inches. Three pairs of prolegs (vs 5 in most caterpillars).',
        'damage_symptoms': 'Defoliation, feeding from leaf edges inward. Can consume entire leaf except main veins.',
        'economic_threshold': '30% defoliation before bloom, 20% defoliation during bloom to pod fill',
        'management_notes': 'More common in southern regions. Pyrethroids or other foliar insecticides. Scout carefully as they blend with foliage.',
    },
    {
        'common_name': 'Thistle Caterpillar (Painted Lady)',
        'scientific_name': 'Vanessa cardui',
        'pest_type': 'insect',
        'description': 'Sporadic defoliator that arrives in waves. Forms webbing at tops of plants. Highly mobile.',
        'lifecycle': 'Migrates north from Mexico in variable numbers. Multiple generations, outbreak years unpredictable.',
        'identification_features': 'Larvae: Yellow-green with black and yellow stripes, spiny, up to 2 inches. Creates silk webbing at plant terminals.',
        'damage_symptoms': 'Webbed terminals, defoliation starting at top of plant. Can cause complete defoliation in outbreak years.',
        'economic_threshold': 'Same as other defoliators: 30% before bloom, 20% during pod fill',
        'management_notes': 'Scout field edges first. Pyrethroids effective. Young larvae easier to control. Outbreak years are sporadic.',
    },
    {
        'common_name': 'Grape Colaspis',
        'scientific_name': 'Colaspis brunnea',
        'pest_type': 'insect',
        'description': 'Larvae feed on roots and nodules, adults cause minor defoliation. Most damage in fields following pasture or hay.',
        'lifecycle': 'One generation per year. Overwinters as larvae. Adults emerge June-July.',
        'identification_features': 'Adults: Small (1/8 inch) bronze-brown beetle. Larvae: white grubs in soil feeding on roots and nodules.',
        'damage_symptoms': 'Stunted, yellow plants. Root pruning. Reduced nodulation. Symptoms similar to nutrient deficiency.',
        'economic_threshold': 'No established threshold. Seedling damage may warrant replanting.',
        'management_notes': 'Seed treatments may provide some protection. Avoid planting soybeans after pasture/hay if possible. Foliar sprays ineffective.',
    }
]

# ============================================================================
# CORN DISEASES
# ============================================================================

CORN_DISEASES = [
    {
        'common_name': 'Gray Leaf Spot',
        'scientific_name': 'Cercospora zeae-maydis',
        'pathogen_type': 'fungal',
        'description': 'Most economically important foliar disease in humid corn-growing regions. Yield losses can exceed 50% in susceptible hybrids.',
        'symptoms': 'Rectangular lesions parallel to leaf veins, gray to tan with darker borders. Lesions expand and coalesce causing leaf death. Starts on lower leaves.',
        'favorable_conditions': 'Warm (75-85°F), humid, cloudy weather. Heavy dew. Reduced tillage with corn residue. Susceptible hybrids.',
        'lifecycle': 'Overwinters on corn residue. Spores spread by wind and rain splash during growing season. Multiple infection cycles possible.',
        'management': 'Resistant hybrids (most important). Crop rotation. Tillage to bury residue. Fungicide applications at VT-R2 if susceptible and conditions favor disease.',
    },
    {
        'common_name': 'Northern Corn Leaf Blight',
        'scientific_name': 'Exserohilum turcicum (Setosphaeria turcica)',
        'pathogen_type': 'fungal',
        'description': 'Common foliar disease in cool, humid regions. Can cause significant yield loss if present before pollination.',
        'symptoms': 'Long (2-6 inches), elliptical, grayish-green to tan lesions. Often cigar-shaped. Start on lower leaves, progress upward.',
        'favorable_conditions': 'Cool (65-80°F), extended periods of high humidity and leaf wetness. Moderate temperatures, frequent dew.',
        'lifecycle': 'Overwinters on corn residue. Spores produced in spring, spread by wind. Secondary cycles during season in favorable conditions.',
        'management': 'Resistant hybrids. Tillage. Crop rotation. Foliar fungicides (QoI + triazole) at V10-VT if disease progressing and conditions favorable.',
    },
    {
        'common_name': 'Southern Corn Leaf Blight',
        'scientific_name': 'Bipolaris maydis (Cochliobolus heterostrophus)',
        'pathogen_type': 'fungal',
        'description': 'More common in southern regions and warmer years. Can be severe in fields with continuous corn.',
        'symptoms': 'Small to medium (1/4 to 1 inch) oval to rectangular lesions, tan with reddish-brown borders. Lesions scattered across leaf.',
        'favorable_conditions': 'Warm (70-90°F), high humidity, heavy dews. Corn-on-corn fields.',
        'lifecycle': 'Overwinters on corn residue. Spores spread by wind during season. Multiple cycles possible in warm, humid conditions.',
        'management': 'Resistant hybrids. Crop rotation. Tillage. Foliar fungicides if disease pressure high before pollination.',
    },
    {
        'common_name': 'Common Rust',
        'scientific_name': 'Puccinia sorghi',
        'pathogen_type': 'fungal',
        'description': 'Common foliar disease, usually appears late season. Can be severe in susceptible hybrids with early onset.',
        'symptoms': 'Small, circular to elongate pustules (rust spots) on both leaf surfaces. Reddish-brown to cinnamon colored. Pustules release rusty spores when rubbed.',
        'favorable_conditions': 'Cool to moderate temperatures (60-75°F), high humidity, frequent dews.',
        'lifecycle': 'Does not overwinter in northern states. Spores blow in from southern states. Alternate host: wood sorrel (Oxalis).',
        'management': 'Resistant hybrids. Usually develops too late for economic damage. Foliar fungicides only if develops before R2 and conditions favor progression.',
    },
    {
        'common_name': 'Southern Rust',
        'scientific_name': 'Puccinia polysora',
        'pathogen_type': 'fungal',
        'description': 'More aggressive than common rust. Can cause rapid yield loss. Increasingly moving north with climate change.',
        'symptoms': 'Small, circular pustules densely packed on upper leaf surface. Light orange to gold color. Pustules smaller and more numerous than common rust.',
        'favorable_conditions': 'Warm temperatures (75-85°F), high humidity. More tropical disease but spreading north.',
        'lifecycle': 'Does not overwinter in US. Spores blow north from Mexico/Caribbean. Can spread rapidly once established.',
        'management': 'Resistant hybrids most important. Fungicides (triazoles + QoI) if detected before R3 and weather favors spread. Scout regularly in southern regions.',
    },
    {
        'common_name': 'Tar Spot',
        'scientific_name': 'Phyllachora maydis',
        'pathogen_type': 'fungal',
        'description': 'Emerging disease in Midwest since 2015. Can cause severe yield loss. Now established in many Corn Belt states.',
        'symptoms': 'Small (1-5mm), raised, circular black spots (stromata) on leaves. Look like specks of tar. May have tan halos (fisheye lesions) in severe cases.',
        'favorable_conditions': 'Cool (60-70°F), wet conditions. High humidity, frequent rain. Extended periods of leaf wetness.',
        'lifecycle': 'Overwinters on corn residue. Spores released during season infect leaves. Disease progresses late season (R3-R6).',
        'management': 'Hybrid tolerance (resistance not yet available). Fungicide applications at VT-R1 in high-risk areas. Crop rotation, tillage may help.',
    },
    {
        'common_name': 'Anthracnose Leaf Blight and Stalk Rot',
        'scientific_name': 'Colletotrichum graminicola',
        'pathogen_type': 'fungal',
        'description': 'Can cause both foliar disease and stalk rot. Stalk rot phase can cause lodging and harvest loss.',
        'symptoms': 'Leaf phase: small, oval lesions with tan centers and reddish-brown borders. Stalk phase: internal stalk discoloration, lodging.',
        'favorable_conditions': 'Warm, humid weather. Stress conditions (drought, nutrient deficiency). Corn-on-corn.',
        'lifecycle': 'Overwinters on corn residue. Spores splash up to lower leaves. Enters stalks through roots or lower nodes.',
        'management': 'Resistant hybrids. Crop rotation. Balanced fertility. Avoid late-season stress. Early harvest if stalk rot present.',
    },
    {
        'common_name': 'Eyespot',
        'scientific_name': 'Aureobasidium zeae (Kabatiella zeae)',
        'pathogen_type': 'fungal',
        'description': 'Common foliar disease, usually minor. Can be severe in sweet corn and susceptible hybrids.',
        'symptoms': 'Small, circular spots with tan to white centers and brown to purple borders. Bulls-eye appearance. May have yellow halos.',
        'favorable_conditions': 'Cool, wet weather. Extended leaf wetness.',
        'lifecycle': 'Overwinters on crop residue. Spores spread by rain splash.',
        'management': 'Usually does not warrant treatment in field corn. Resistant hybrids. Fungicides only if severe in susceptible hybrids.',
    },
    {
        'common_name': 'Goss\'s Wilt',
        'scientific_name': 'Clavibacter michiganensis subsp. nebraskensis',
        'pathogen_type': 'bacterial',
        'description': 'Bacterial disease causing both leaf blight and systemic wilt. Can cause significant yield loss. "Freckles" on leaves are diagnostic.',
        'symptoms': 'Water-soaked lesions with dark green to black margins. Lesions become tan. Distinctive dark "freckles" in lesions. Systemic wilt in severe cases.',
        'favorable_conditions': 'Warm weather following storm damage or hail. Enters through wounds.',
        'lifecycle': 'Overwinters in crop residue and on seed. Spread by wind, water, equipment.',
        'management': 'Resistant hybrids essential. Crop rotation. Avoid mechanical damage. No chemical control (bacterial). Avoid high nitrogen on susceptible hybrids.',
    },
    {
        'common_name': 'Stewart\'s Wilt',
        'scientific_name': 'Pantoea stewartii',
        'pathogen_type': 'bacterial',
        'description': 'Bacterial disease vectored by corn flea beetle. More common in southern corn-growing areas and sweet corn.',
        'symptoms': 'Long, pale green to yellow streaks with wavy margins. Seedling wilt in susceptible hybrids. Leaf blight phase in older plants.',
        'favorable_conditions': 'Warm winters allow flea beetle survival. Early season infections most damaging.',
        'lifecycle': 'Overwinters in corn flea beetle. Beetle transmits bacteria while feeding. Can also spread through seed.',
        'management': 'Resistant hybrids. Seed treatment insecticides target flea beetles. More important in sweet corn than field corn.',
    },
    {
        'common_name': 'Diplodia Ear Rot',
        'scientific_name': 'Stenocarpella maydis',
        'pathogen_type': 'fungal',
        'description': 'Major ear rot causing poor grain quality and mycotoxins. Also causes stalk rot and seedling blight.',
        'symptoms': 'White mold starting at base of ear, progressing upward. Husks bleached white. Black pycnidia (fungal fruiting bodies) on kernels and cob.',
        'favorable_conditions': 'Warm, wet conditions during and after pollination. Corn-on-corn. Stress during grain fill.',
        'lifecycle': 'Overwinters on corn residue. Spores infect through silks or wounds.',
        'management': 'Crop rotation. Tillage. Resistant hybrids. Proper fertility and stress management. Early harvest, dry grain promptly.',
    },
    {
        'common_name': 'Gibberella Ear Rot',
        'scientific_name': 'Fusarium graminearum',
        'pathogen_type': 'fungal',
        'description': 'Major ear rot producing dangerous mycotoxins (DON/vomitoxin). Can make grain unmarketable.',
        'symptoms': 'Pink to reddish mold starting at ear tip. Often scattered infected kernels. May have white mycelium.',
        'favorable_conditions': 'Cool, wet weather during and after pollination. Insect or bird damage to ears.',
        'lifecycle': 'Overwinters on corn and small grain residue. Spores infect through silks, wounds, or husk openings.',
        'management': 'Hybrid selection (tight husks, upright ears). Crop rotation away from small grains. Fungicide at silk (limited efficacy). Control ear-feeding insects. Early harvest.',
    },
    {
        'common_name': 'Aspergillus Ear Rot',
        'scientific_name': 'Aspergillus flavus',
        'pathogen_type': 'fungal',
        'description': 'Hot weather ear rot producing aflatoxin. Major concern in southern regions and hot, droughty years.',
        'symptoms': 'Greenish-yellow to olive-green mold on kernels. Powdery appearance. Usually scattered kernels.',
        'favorable_conditions': 'Hot (>85°F), drought stress during grain fill. Insect damage.',
        'lifecycle': 'Survives in soil. Spores infect damaged kernels, especially drought-stressed.',
        'management': 'Irrigation in drought. Control insects (especially corn earworm, beetles). Avoid drought stress. Early harvest. Monitor for aflatoxin.',
    }
]

# ============================================================================
# SOYBEAN DISEASES
# ============================================================================

SOYBEAN_DISEASES = [
    {
        'common_name': 'White Mold (Sclerotinia Stem Rot)',
        'scientific_name': 'Sclerotinia sclerotiorum',
        'pathogen_type': 'fungal',
        'description': 'Most damaging soybean disease in northern regions. Yield losses can exceed 40%. Difficult to manage.',
        'symptoms': 'Tan to brown lesions on stems, usually near nodes. White cottony mold on stems and pods. Hard black sclerotia form inside stems and on surface.',
        'favorable_conditions': 'Cool (60-70°F), wet weather during flowering. Dense canopy. History of white mold. Narrow rows.',
        'lifecycle': 'Overwinters as sclerotia in soil. Apothecia (mushrooms) form, release spores that infect flowers. Stems colonized from flowers.',
        'management': 'No resistant varieties. Wider row spacing. Fungicide at R1-R2 (expensive, variable efficacy). Rotation with non-hosts. Avoid high populations.',
    },
    {
        'common_name': 'Sudden Death Syndrome (SDS)',
        'scientific_name': 'Fusarium virguliforme',
        'pathogen_type': 'fungal',
        'description': 'Increasing problem in Midwest. Root rot causes foliar symptoms. Yield losses can be severe.',
        'symptoms': 'Interveinal chlorosis (yellowing) and necrosis (browning) on leaves. Green veins remain. Premature defoliation. Roots rotted with blue-gray interior.',
        'favorable_conditions': 'Cool, wet soils early season followed by warm, wet mid-late season. Compaction. SCN increases severity. Low-lying areas.',
        'lifecycle': 'Soil-borne fungus infects roots early. Produces toxin that moves to leaves, causing symptoms mid-late season (R3-R5).',
        'management': 'Partial resistance (critical). SCN management. Seed treatment with ILeVO (fluopyram). Drainage and compaction management. Early planting.',
    },
    {
        'common_name': 'Soybean Cyst Nematode (SCN)',
        'scientific_name': 'Heterodera glycines',
        'pathogen_type': 'nematode',
        'description': 'Most economically damaging soybean pathogen. Often causes yield loss without obvious symptoms. Present in most fields.',
        'symptoms': 'Often no aboveground symptoms. Stunted, yellow patches in field. Small white to yellow cysts (females) visible on roots in mid-summer.',
        'favorable_conditions': 'Continuous soybeans. Sandy soils. Present in most fields but varies by area.',
        'lifecycle': 'Eggs in cysts overwinter in soil. Juveniles invade roots in spring, develop into females. 3-4 generations per year.',
        'management': 'SCN-resistant varieties (rotate resistance sources - PI88788, Peking, etc.). Crop rotation. Soil sampling to monitor populations. Seed treatments.',
    },
    {
        'common_name': 'Brown Stem Rot',
        'scientific_name': 'Phialophora gregata (Cadophora gregata)',
        'pathogen_type': 'fungal',
        'description': 'Soil-borne disease causing vascular wilt. Yield loss without foliar symptoms possible.',
        'symptoms': 'Interveinal chlorosis and necrosis on upper leaves (similar to SDS but starts from top). Brown discoloration inside stem. Pith remains white (vs. solid brown in Phytophthora).',
        'favorable_conditions': 'Cool temperatures during growing season. History of disease. Continuous soybeans.',
        'lifecycle': 'Overwinters in crop residue. Infects roots, colonizes vascular tissue.',
        'management': 'Resistant varieties. Crop rotation. No chemical control available.',
    },
    {
        'common_name': 'Frogeye Leaf Spot',
        'scientific_name': 'Cercospora sojina',
        'pathogen_type': 'fungal',
        'description': 'Common foliar disease. Can cause significant defoliation and yield loss if not managed.',
        'symptoms': 'Circular spots with gray to tan centers and dark purple to reddish-brown borders. "Frogeye" appearance. Lesions may have yellow halos.',
        'favorable_conditions': 'Warm (70-80°F), humid weather. Extended leaf wetness. Susceptible varieties.',
        'lifecycle': 'Overwinters on crop residue. Spores spread by rain splash and wind. Multiple cycles during season.',
        'management': 'Resistant varieties (Rcs genes). Crop rotation. Tillage. Foliar fungicides (QoI + triazole) if susceptible variety and conditions favor disease.',
    },
    {
        'common_name': 'Septoria Brown Spot',
        'scientific_name': 'Septoria glycines',
        'pathogen_type': 'fungal',
        'description': 'Most common soybean foliar disease. Usually minor but can cause premature defoliation.',
        'symptoms': 'Small, irregular brown spots on leaves, often with yellow halos. Starts on lower leaves, progresses upward.',
        'favorable_conditions': 'Warm, humid weather. Dense canopy.',
        'lifecycle': 'Overwinters on crop residue. Spores spread by rain splash.',
        'management': 'Usually does not require treatment. Crop rotation. Foliar fungicides only warranted if severe before R5 and moving up canopy rapidly.',
    },
    {
        'common_name': 'Bacterial Blight',
        'scientific_name': 'Pseudomonas savastanoi pv. glycinea',
        'pathogen_type': 'bacterial',
        'description': 'Common bacterial disease. Usually minor but can be severe in susceptible varieties.',
        'symptoms': 'Small, angular spots (limited by veins) with yellow halos. Spots may have water-soaked appearance. Leaf distortion.',
        'favorable_conditions': 'Cool, wet weather. Wind and rain spread bacteria. Enters through wounds.',
        'lifecycle': 'Overwinters on seed and crop residue. Spread by rain splash and wind.',
        'management': 'Resistant varieties. Pathogen-free seed. Crop rotation. No chemical control (bacterial).',
    },
    {
        'common_name': 'Cercospora Leaf Blight',
        'scientific_name': 'Cercospora kikuchii',
        'pathogen_type': 'fungal',
        'description': 'Late-season foliar disease and seed pathogen. Can reduce seed quality (purple seed stain).',
        'symptoms': 'Purple to reddish-brown discoloration on upper leaves late season. Leathery leaves that remain attached. Purple staining on seed.',
        'favorable_conditions': 'Warm, humid weather late season. Stressed plants.',
        'lifecycle': 'Seed-borne and overwinters on residue. Infects leaves and seeds.',
        'management': 'Fungicide seed treatment. Foliar fungicides at R3-R5 in high-pressure areas. Pathogen-free seed. Avoid late planting.',
    },
    {
        'common_name': 'Anthracnose',
        'scientific_name': 'Colletotrichum truncatum and others',
        'pathogen_type': 'fungal',
        'description': 'Can cause stem blight, pod blight, and seedling damping-off. More common in warmer regions.',
        'symptoms': 'Stem lesions with dark borders. Irregular brown blotches on pods. Black fungal fruiting bodies (acervuli) on stems and pods.',
        'favorable_conditions': 'Warm, wet weather. Wounded tissue. Stressed plants.',
        'lifecycle': 'Overwinters on crop residue. Spores spread by rain splash.',
        'management': 'Crop rotation. Tillage. Fungicide seed treatments. Foliar fungicides rarely economical.',
    },
    {
        'common_name': 'Phytophthora Root and Stem Rot',
        'scientific_name': 'Phytophthora sojae',
        'pathogen_type': 'oomycete',
        'description': 'Water mold causing root and stem rot. Can cause complete plant death. Multiple races.',
        'symptoms': 'Pre- and post-emergence damping-off. Brown, water-soaked stem lesions starting at soil line. Sudden wilting and plant death. Dark brown roots.',
        'favorable_conditions': 'Saturated soils. Poorly drained areas. Cool to warm temperatures.',
        'lifecycle': 'Survives in soil as oospores. Zoospores released in saturated soils swim to roots and germinate.',
        'management': 'Partial resistance (Rps genes - know field races). Drainage. Seed treatments (mefenoxam, ethaboxam). Foliar fungicides ineffective.',
    },
    {
        'common_name': 'Soybean Rust',
        'scientific_name': 'Phakopsora pachyrhizi',
        'pathogen_type': 'fungal',
        'description': 'Potential to cause severe yield loss. Established in southern US, rarely reaches northern states.',
        'symptoms': 'Small pustules on lower leaf surface. Tan to dark brown lesions with open pustules. Premature defoliation.',
        'favorable_conditions': 'Warm, humid conditions. Cannot survive winter in continental US north of Gulf states.',
        'lifecycle': 'Spores blow north from overwintering sites in Gulf states. Multiple cycles during season in favorable conditions.',
        'management': 'Monitor rust reports. Fungicide applications (triazoles + QoI) if detected and conditions favor spread. Usually not economical in northern states.',
    },
    {
        'common_name': 'Charcoal Rot',
        'scientific_name': 'Macrophomina phaseolina',
        'pathogen_type': 'fungal',
        'description': 'Hot, dry weather disease. Causes root and stem rot. More severe under drought stress.',
        'symptoms': 'Premature wilting and death. Grayish-brown discoloration of stem and roots. Tiny black sclerotia in stem give charcoal appearance.',
        'favorable_conditions': 'Hot (>85°F), drought-stressed plants. Sandy soils. Mid-late season.',
        'lifecycle': 'Survives as sclerotia in soil and residue. Infects roots and lower stems under stress.',
        'management': 'No resistant varieties. Irrigation. Avoid plant stress. Crop rotation limited benefit. No chemical control.',
    },
    {
        'common_name': 'Pod and Stem Blight',
        'scientific_name': 'Diaporthe phaseolorum and D. longicolla',
        'pathogen_type': 'fungal',
        'description': 'Late-season stem disease and seed quality issue. Can cause pods to remain attached at maturity.',
        'symptoms': 'Linear rows of black pycnidia on stems and pods. Shriveled, low-quality seed. Pods remain attached. Stems appear silvery.',
        'favorable_conditions': 'Warm, humid conditions late season.',
        'lifecycle': 'Overwinters on crop residue. Seed-borne. Infects stems and pods late season.',
        'management': 'Crop rotation. Tillage. Fungicide seed treatment. Pathogen-free seed. Usually not economical to spray.',
    },
    {
        'common_name': 'Downy Mildew',
        'scientific_name': 'Peronospora manshurica',
        'pathogen_type': 'oomycete',
        'description': 'Usually minor disease. Can affect seed quality. More common in cool, wet conditions.',
        'symptoms': 'Pale green to yellow spots on upper leaf surface with gray-purple fuzzy growth on lower surface. Systemic infection causes yellowing.',
        'favorable_conditions': 'Cool, wet weather. High humidity.',
        'lifecycle': 'Seed-borne and overwinters on residue. Spores spread by wind.',
        'management': 'Resistant varieties. Pathogen-free seed. Fungicide seed treatment. Usually does not warrant foliar treatment.',
    }
]

# This data will be used to populate the database with professional-grade pest and disease information
